print("Hola mundo")
print("Linea 1")
print("Linea 2 main")
print("Linea 3 main")
print("Linea 4 main")
print("Linea 2")
print("Linea 3")
print("Linea 4")
print("Linea 5")
print("Linea 6")
print("Linea 7")
print("Linea 8")

